### ISSUE TITLE
As migration facilitator I need to compare two lists of hashed values

### ISSUE THREAD

**Issue by mjy** [sfborg/sfid#3]
The current format is MD5

* One list (A) is derived from those hashes generated by TW, they are calculated when an image is added
* A second list (B) is calculated based on crawling a file-system, it includes two columns, the hash, and the full path + file
  * The file system contains not only the target images, but other derivations
     *  We only need the hash of the target (those like path `.../original/<filename>`

When I have two lists, then I create list C, which is composed of the paths, one per line, of all B that have no corresponding hash in A.

**Comment by dimus** [comment]
So from the point of `sfid` we need to add an option to return back MD5 hash generated from the content of the file, similar to sha256 and UUID v5? For example
`sfid -m file/path.jpg` would output

`file/path.jpg\tmd5hash`?

**Comment by mjy** [comment]
Yes. Which we can already do with things like open-ssl `md5` apparently.  Maybe we are over-thinking a bash script...

**Comment by dimus** [comment]
I was thinking the same :) May be bash script + parallel would do the trick

**Comment by dimus** [comment]
0.1.1 has md5 instead of sha256. 

may be `find | xargs md5sum` is enough?
